[2024-03-28T17:46:11.184+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cryptocurrency_data_pipeline.merge_import_into_final_table scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-03-28T17:46:13.572+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cryptocurrency_data_pipeline.merge_import_into_final_table scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-03-28T17:46:13.883+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-03-28T17:46:34.200+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): merge_import_into_final_table> on 2024-01-09 00:00:00+00:00
[2024-03-28T17:46:40.987+0000] {standard_task_runner.py:60} INFO - Started process 543 to run task
[2024-03-28T17:46:43.607+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2024-03-28T17:46:47.854+0000] {process_utils.py:131} INFO - Sending 15 to group 543. PIDs of all processes in the group: [543]
[2024-03-28T17:46:48.106+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 543
[2024-03-28T17:46:49.868+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=543, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='17:46:40') (543) terminated with exit code -15
[2024-03-28T17:46:50.181+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 143
