[2024-03-29T17:00:53.316+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_scheduling.hello scheduled__2022-03-01T00:00:00+00:00 [queued]>
[2024-03-29T17:00:53.335+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_scheduling.hello scheduled__2022-03-01T00:00:00+00:00 [queued]>
[2024-03-29T17:00:53.337+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-03-29T17:00:53.377+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): hello> on 2022-03-01 00:00:00+00:00
[2024-03-29T17:00:53.388+0000] {standard_task_runner.py:60} INFO - Started process 2959 to run task
[2024-03-29T17:00:53.400+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'demo_scheduling', 'hello', 'scheduled__2022-03-01T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/demo_scheduling.py', '--cfg-path', '/tmp/tmp0jwa_i_r']
[2024-03-29T17:00:53.414+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask hello
[2024-03-29T17:00:53.553+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-03-29T17:00:53.699+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_scheduling.hello scheduled__2022-03-01T00:00:00+00:00 [running]> on host c4cb237119ff
[2024-03-29T17:00:54.878+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='domwatcharin' AIRFLOW_CTX_DAG_ID='demo_scheduling' AIRFLOW_CTX_TASK_ID='hello' AIRFLOW_CTX_EXECUTION_DATE='2022-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-03-01T00:00:00+00:00'
[2024-03-29T17:00:54.906+0000] {demo_scheduling.py:9} INFO - Hello
[2024-03-29T17:00:54.911+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-03-29T17:00:55.003+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=demo_scheduling, task_id=hello, execution_date=20220301T000000, start_date=20240329T170053, end_date=20240329T170055
[2024-03-29T17:00:55.097+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-29T17:00:55.229+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
